### ISSUE TITLE
Publish beta once PE->AE migrations are working

### ISSUE THREAD

**Issue by rrrene** [atlas-engine/AtlasEngine.FullstackServer#20]
Wie im Daily besprochen: Die  erste  Beta sollte  veröffentlicht werden, sobald die Migrationen funktionieren.

Als Definition von "funktionieren" würde ich folgende vorschlagen: die dann aktuelle AtlasEngine-Alpha mit den Migrationen ist Teil eines BPMN-Studios in Alpha-Version und wenn ich von BPMN Studio 5 Alpha auf diese BPMN Studio 6 Alpha upgraded, dann laufen die Migrationen korrekt durch.

Dann sollte es natürlich auch eine entsprechende BPMN Studio Beta-Version geben, die das 5Minds-Team testen kann :+1:

**Comment by ElRaptorus** [comment]
Done!
