### ISSUE TITLE
Replace addict-ioc with InversifyJS

### ISSUE THREAD

**Issue by rrrene** [atlas-engine/AtlasEngine.FullstackServer#3]
@moellenbeck hatte vor dem Hackathon angeregt, die Weiterverwendung von `addict-ioc` kritisch zu hinterfragen und hatte angeregt, stattdessen [Inversify.js](http://inversify.io/) zu nutzen.

Nachdem wir unseren Hackathon so erfolgreich bestritten haben, glaube ich, dass wir auch diesen Schritt jetzt gehen müssen. `addict-ioc` ist ein Experiment von 5Minds, dass nunmehr einer Ablösung bedarf, da es nicht nur eine proprietäre Lösung für ein allgemein gelöstes Problem darstellt, sondern auch die „concerns“ Konfiguration und Dependency Injection in einer stark koppelnden Art vermischt, was unsere Software von seiner sehr unreifen Art des Konfigurationsmanagements abhängig macht (hier deutet bereits der Name daraufhin, dass das evtl. Absicht ist). Vor  dem Hintergrund unserer weiteren Pläne ist es angebracht, jetzt doch den IoC-Container zu nutzen, der bereits vor drei Jahren Platzhirsch war, als wir unser Experiment begonnen haben. 👍

@elraptorus Bitte setz dich Montag mal eine Stunde hin und schreib auf, was hierfür zu tun ist. 

Wahrscheinlich müssen wir ja die beiden „concerns“ DI und Configuration separieren, sprich ich könnte mir vorstellen, dass der von dir zu formulierenden Plan die Form

> In allen Repos müssen folgende Schritte gemacht werden, um die Dependiencies mit Inversify anstatt `addict-ioc` zu injecten.
>
> Für alle durch `addict-ioc` konfigurierten Elemente muss folgendes unternommen werden, damit sie nicht mehr durch `addict-ioc` konfiguriert werden.

**Wichtig**: Dieses von mir skizzierte Vorgehen ist nur ein Bauchgefühl und ich kann völlig falsch liegen. In diesem Fall einfach anders aufschreiben. Insbesondere wäre denkbar, dass wir vielleicht `addict-ioc` in einem ersten Schritt für DI durch Inversify ablösen, aber noch zum Konfigurieren nutzen und dann in einem zweiten Schritt die Konfiguration neu denken (um diese „separation of concerns“ in ihrer Umsetzung zu entzerren).

@steffenkn Guck dir, wenn du Montag wieder da bist, ruhig schon mal die AtlasEngine an: https://github.com/atlas-engine/ContributionGuidelines/tree/develop/scripts/setup
Ich könnte mir gut vorstellen, dass du die Umsetzung dieses Issues übernehmen kannst.

**Comment by rrrene** [comment]
@elraptorus Wenn das hier das falsche Repo für dieses Issue ist, bitte melden, dann verschiebe ich es. Ich dachte nur, dass im FullstackServer solche „cross cutting concerns“ zusammen kommen. 👍

**Comment by ElRaptorus** [comment]
Um das umzusetzen, müsste man durch sämtliche Pakete gehen, die über ein `ioc_module` verfügen - effektiv alle Pakete, abgesehen von den `Contracts` - und die Registrierungen an die inversify Semantik anpassen. 

D.h. jede Klasse, die in den Container soll, benötigt ein `@injectable()` decorator und jede in den Constructor gegebene Dependency ein `@inject('DependencyName')` decorator. 

Am Beispiel des `ExecuteProcessServices` würde das dann in etwa so aussehen (sofern alle Registrierungen ihre aktuellen Namen beibehalten): 

```ts
`@injectable()
export class ExecuteProcessService implements IExecuteProcessService {

  private readonly eventAggregator: IEventAggregator;
  private readonly flowNodeHandlerFactory: IFlowNodeHandlerFactory;
  private readonly identityService: IIdentityService;

  private readonly processInstanceStateHandlingFacade: ProcessInstanceStateHandlingFacade;
  private readonly processDefinitionRepository: IProcessDefinitionRepository;

  constructor(
    @inject('EventAggregator') eventAggregator: IEventAggregator,
    @inject('FlowNodeHandlerFactory') flowNodeHandlerFactory: IFlowNodeHandlerFactory,
    @inject('IdentityService') identityService: IIdentityService,
    @inject('ProcessInstanceStateHandlingFacade') processInstanceStateHandlingFacade: ProcessInstanceStateHandlingFacade,
    @inject('CoreDomain.ProcessDefinitionRepository') processDefinitionRepository: IProcessDefinitionRepository,
  ) {
    this.eventAggregator = eventAggregator;
    this.flowNodeHandlerFactory = flowNodeHandlerFactory;
    this.identityService = identityService;
    this.processInstanceStateHandlingFacade = processInstanceStateHandlingFacade;
    this.processDefinitionRepository = processDefinitionRepository;
  }
```

Die `ioc_module` Dateien könnten wir dann benutzen um die Klassen am Container zu registrieren. 

Das könnte dann z.B. so aussehen: 

```js
function registerIncontainer(container) {
    container.bind('ExecuteProcessService')
      .to(ExecuteProcessService)
      .inSingletonScope(); // Für die Klassen, die als Singleton laufen sollen.
}
```

Die Domain Anwendungen, bzw. der FullStack-Server kann dann wie gehabt den Container initialisieren und ihn an die Pakete weiterreichen, die über ein `ioc_module` verfügen.

Für die Klassen, die Tags benutzen (z.B. Socket Endpoints und HttpRouter), 


Bzgl. der Config würde ich vorschlagen, dass wir eine Art `ConfigurationService` implementieren, der als Singleton im IoC Container registriert wird und mit Hilfe von `nconf` auf Anfrage Konfiguratonen ausliest und zurück gibt. 

Das könnte z.B. so aussehen: 

```ts
`@injectable()
export class SomeClassThatNeedsConfigs {

  private config: SomeConfigType;

  private readonly configurationService: IConfigurationService;

  constructor(
    @inject('ConfigurationService') configurationService: IConfigurationService,
  ) {
    this.configurationService = configurationService;
    this.config = this.configurationService.get('some_config_key');
  }
```
