### ISSUE TITLE
🐛Interrupting Boundary Events brechen die Ausführung von CallActivities nicht ab

### ISSUE THREAD

**Issue by alexanderkasten** [atlas-engine/AtlasEngine.FullstackServer#44]
## Description

Ein TimerBoundaryEvent bricht die Ausführung einer CallActivity bzw der ProzessInstanz hinter der CallActivity nicht ab. Die Prozessinstanz sollte eigentlich terminiert werden.
Die CallActivity an der das TimerBoundaryEvent hängt, wird aber schon auf finished gesetzt und erhält auch einen onExit Token. 

Der Bug existiert auch in der aktuellen ProcessEngine.

## Possible solution

Die durch die CallActivity gestartete Prozessinstanz terminieren.

**Comment by ElRaptorus** [comment]
Das ist nicht nur ein Issue mit Timer Boundary Events, sondern interrupting Boundary Events im allgemeinen. 
Eigentlich müsste hier ein beim `interrupt` der CallActivity ein Terminate Signal an den Subprozess geschickt werden.
